GET https://api.smuglinks.com/api/link/get-all
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

###
GET https://api.smuglinks.com/api/subscription/get-all
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

###
POST https://api.smuglinks.com/api/admin/subscriptions/create-plan
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx

{
    "type": "Starter",
    "name": "Free",
    "description": "This is free plan with this you can do severel things.",
    "duration": 7,
    "prices":[
        {
            "country_code":"INR",
            "amount":0,
        },
        {
            "country_code":"US",
            "amount":0,
        },
        {
            "country_code":"UK",
            "amount":0,
        }
    ]
}

###
POST https://api.smuglinks.com/api/user/subscribe-to-plan
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

{
    "plan_id":17,
    "razorpay_payment_id":"absdkfasfdajdsfljasdf"
}

###
POST https://api.smuglinks.com/api/common/web-link
Content-Type: application/json

{
    "username":"amanshaikh"
}