GET https://api.smuglinks.com/api/link/get-all
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

###
GET https://api.smuglinks.com/api/subscription/get-all
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

###
POST https://api.smuglinks.com/api/admin/subscriptions/create-plan
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx

{
    "type": "Starter",
    "name": "Free",
    "description": "This is free plan with this you can do severel things.",
    "duration": 7,
    "prices":[
        {
            "country_code":"INR",
            "amount":0,
        },
        {
            "country_code":"US",
            "amount":0,
        },
        {
            "country_code":"UK",
            "amount":0,
        }
    ]
}

###
POST https://api.smuglinks.com/api/user/subscribe-to-plan
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

{
    "plan_id":17,
    "razorpay_payment_id":"absdkfasfdajdsfljasdf"
}

###
POST https://api.smuglinks.com/api/common/web-link
Content-Type: application/json

{
    "username":"sheikhaman"
}

###
GET https://api.smuglinks.com/api/link/find/2
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

{
    "id":2
}

###
POST https://api.smuglinks.com/api/link/delete
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

{
    "id":1
}

###
GET https://api.smuglinks.com/api/product/find/6
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json


###
POST https://api.smuglinks.com/api/product/edit
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

{
    "id": 7,
    "name": "a bc sdf",
    "description": "this is description here there asdfa sdfas df",
    "category": "sample",
    "action": "link",
    "link": "https://smuglinks.com",
    "btn_name": "Order",
    "enabled":false
}


###
POST https://api.smuglinks.com/api/admin/common/login
Content-Type: application/json

{
    "email":"aadil@smug.link",
    "password":"aadil@jagli"
}


###
POST https://api.smuglinks.com/api/user/update-tab-name
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

{
    "tab_name":"My Distributes"
}



###
POST https://api.smuglinks.com/api/admin/add-admin
uid : KH8lkbHWycIxEUiqxEDMWMfmFyxmK7i1Szhgeg9w1OSeTACmkNOtwwZcyOeeprRh
Content-Type: application/json

{
    "email":"aadil@smug.link",
    "password":"aadil@jagli",
    "name":"Aadil Jagliwala"
}
###
DELETE https://api.smuglinks.com/api/admin/subscription/delete-subscription/5
uid : KH8lkbHWycIxEUiqxEDMWMfmFyxmK7i1Szhgeg9w1OSeTACmkNOtwwZcyOeeprRh
Content-Type: application/json

###
POST https://api.smuglinks.com/api/admin/subscription/create-plan
uid : KH8lkbHWycIxEUiqxEDMWMfmFyxmK7i1Szhgeg9w1OSeTACmkNOtwwZcyOeeprRh
Content-Type: application/json

{
    "name":"Paid Plan",
    "type":"Premium",
    "description":"in this plan you can get all the premium things",
    "prices":[
        {
            "country_code":"INR",
            "amount":699
        },
        {
            "country_code":"US",
            "amount":10
        },
        {
            "country_code":"UK",
            "amount":10
        }
    ],
    "duration":365
}
###
GET https://api.smuglinks.com/api/admin/theme/get-all
uid : KH8lkbHWycIxEUiqxEDMWMfmFyxmK7i1Szhgeg9w1OSeTACmkNOtwwZcyOeeprRh
Content-Type: application/json
###

POST https://api.smuglinks.com/api/admin/theme/add-theme
uid : KH8lkbHWycIxEUiqxEDMWMfmFyxmK7i1Szhgeg9w1OSeTACmkNOtwwZcyOeeprRh
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="img"; filename="C:/Users/Acer/Downloads/download.jpg"
Content-Type: image/jpeg

--boundary
Content-Disposition: form-data; name="name"

New Theme
--boundary
Content-Disposition: form-data; name="description"

This is a new theme description.
--boundary
Content-Disposition: form-data; name="type"

Premium
--boundary--

###
GET https://api.smuglinks.com/api/link/analytics
uid : OXFoDfIW1871485gBq1umSDphzrjnFGxI7DcQdICPcnkK4l5jt9Oig64DqaTIgrx
Content-Type: application/json

